project_id: "881724"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: "."
preserve_hierarchy: true

files:
  - source: "/packages/i18n/locales/en-US/*.json"
    translation: "/packages/i18n/locales/%locale%/%original_file_name%"
    languages_mapping:
      locale:
        "en-GB": "en_GB"
        "es-ES": "es_ES"
        "es-MX": "es_MX"
        "fr":    "fr"
        "it":    "it"
        "pt-BR": "pt_BR"
        "pt-PT": "pt_PT"
